version: "3.8"

services:
  footballdata_db:
    image: postgres
    container_name: footballdata_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=footballdata
    ports:
      - "7898:5432"

  footballdata_backend:
    container_name: footballdata_backend
    build: .
    entrypoint: "/usr/src/app/scripts/entrypoint.sh"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=footballdata_db
      - DB_PORT=5432
      - DB_NAME=footballdata
      - DB_USER=postgres
      - DB_PASS=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - footballdata_db
      - redis
    ports:
      - "7171:8000"

  redis:
    image: redis:alpine
    container_name: redisalpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A footballdata worker -l info
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=footballdata_db
      - DB_PORT=5432
      - DB_NAME=footballdata
      - DB_USER=postgres
      - DB_PASS=postgres
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - footballdata_db
      - redis
      - footballdata_backend