# Generated by Django 4.1 on 2022-08-28 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("date_of_birth", models.DateTimeField(null=True)),
                ("nationality", models.CharField(blank=True, max_length=500, null=True)),
                ("fd_id", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "coaches",
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("area_name", models.CharField(max_length=500)),
                ("code", models.CharField(max_length=30)),
                ("fd_id", models.IntegerField()),
            ],
            options={
                "db_table": "competitions",
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=500)),
                ("tla", models.CharField(blank=True, max_length=30, null=True)),
                ("short_name", models.CharField(blank=True, max_length=500, null=True)),
                ("area_name", models.CharField(max_length=500)),
                ("address", models.CharField(blank=True, max_length=500, null=True)),
                ("fd_id", models.IntegerField()),
                ("competitions", models.ManyToManyField(related_name="teams", to="api.competition")),
            ],
            options={
                "db_table": "teams",
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("position", models.CharField(blank=True, max_length=500, null=True)),
                ("date_of_birth", models.DateTimeField(null=True)),
                ("nationality", models.CharField(blank=True, max_length=500, null=True)),
                ("fd_id", models.IntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="players", to="api.team"
                    ),
                ),
            ],
            options={
                "db_table": "players",
                "ordering": ("created",),
            },
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(fields=["code"], name="competition_code_4af0d5_idx"),
        ),
        migrations.AddField(
            model_name="coach",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="coaches", to="api.team"
            ),
        ),
    ]
